[package]
name = "fillyfoal-system"
description = "fillyfoal's dissectors for operating system artifacts, forensic records, mobile platforms and machine learning models"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fillyfoal-core.workspace = true
fillyfoal-archive.workspace = true
fillyfoal-data.workspace = true
fillyfoal-exec.workspace = true
fillyfoal-image.workspace = true
fillyfoal-text.workspace = true

[lints]
workspace = true
