[package]
name = "fillyfoal-security"
description = "fillyfoal's dissectors for ASN.1 and PKI objects, keys, keystores, password vaults and packet captures"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fillyfoal-core.workspace = true
fillyfoal-text.workspace = true

[lints]
workspace = true
