[package]
name = "fillyfoal-codec"
description = "fillyfoal's byte primitives, diagnostics, spans and codecs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
include = ["/src/**/*.rs", "/src/codec/brotli_dictionary.bin"]

[dependencies]

[lints]
workspace = true
