"""Generates the G-code fixtures: a small PrusaSlicer-style text G-code
(written here, in the layout of PrusaSlicer 2.8 output) and its binary
conversions by libbgcode.

    uv run --no-project --with pillow \
        --with "pybgcode @ git+https://github.com/prusa3d/libbgcode@d4da9073616d70a43c151e8c1d7fbff879d2e08a" \
        python tests/data/bgcode/make_bgcode.py

Writes:
- tests/fixtures/synthetic/gcode/prusaslicer.gcode (the text source),
- tests/fixtures/external/bgcode/*.bgcode (libbgcode `from_ascii_to_binary`
  with each compression, G-code encoding and checksum type),
- tests/data/bgcode/*.ref.gcode (libbgcode `from_binary_to_ascii` of each,
  which the tests compare our decoded G-code blocks against).
"""

import base64
import io
import os

import pybgcode
from pybgcode import _bgcode
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
SYN = os.path.join(ROOT, "tests/fixtures/synthetic/gcode")
EXT = os.path.join(ROOT, "tests/fixtures/external/bgcode")
REF = os.path.join(ROOT, "tests/data/bgcode")


def thumbnail(fmt, size):
    im = Image.new("RGB", size, (240, 240, 240))
    for x in range(size[0] // 4, 3 * size[0] // 4):
        for y in range(size[1] // 4, 3 * size[1] // 4):
            im.putpixel((x, y), (250, 104, 49))
    out = io.BytesIO()
    im.save(out, fmt, **({"quality": 50} if fmt == "JPEG" else {}))
    return out.getvalue()


def thumbnail_block(tag, data, size):
    text = base64.b64encode(data).decode()
    lines = [f"; {tag} begin {size[0]}x{size[1]} {len(text)}"]
    lines += ["; " + text[i : i + 78] for i in range(0, len(text), 78)]
    lines += [f"; {tag} end", ";", ""]
    return lines


def source():
    lines = ["; generated by PrusaSlicer 2.8.1 on 2025-03-14 at 09:26:53 UTC", "", ""]
    for key, value in [
        ("printer_model", "MK4S"),
        ("filament_type", "PLA"),
        ("nozzle_diameter", "0.4"),
        ("bed_temperature", "60"),
        ("fill_density", "15%"),
        ("layer_height", "0.2"),
        ("temperature", "215"),
        ("max_layer_z", "0.60"),
        ("extruder_colour", '""'),
    ]:
        lines.append(f"; {key} = {value}")
    lines += ["", ""]
    lines += thumbnail_block("thumbnail", thumbnail("PNG", (16, 16)), (16, 16))
    lines += thumbnail_block("thumbnail_QOI", thumbnail("QOI", (12, 12)), (12, 12))
    lines += thumbnail_block("thumbnail_JPG", thumbnail("JPEG", (8, 8)), (8, 8))
    lines += [
        "; external perimeters extrusion width = 0.45mm",
        "; perimeters extrusion width = 0.45mm",
        "",
        "M73 P0 R1",
        "M201 X4000 Y4000 Z200 E2500 ; sets maximum accelerations, mm/sec^2",
        "M203 X300 Y300 Z40 E100 ; sets maximum feedrates, mm / sec",
        "M107",
        ";TYPE:Custom",
        'M862.3 P "MK4S" ; printer model check',
        "M104 S215 ; set extruder temp",
        "M140 S60 ; set bed temp",
        "G28 ; home all without mesh bed level",
        "M190 S60 ; wait for bed temp",
        "M109 S215 ; wait for extruder temp",
        "G21 ; set units to millimeters",
        "G90 ; use absolute coordinates",
        "M83 ; extruder relative mode",
        "G1 Z.2 F720",
        "G92 E0",
    ]
    for layer in range(3):
        z = 0.2 * (layer + 1)
        lines += [";LAYER_CHANGE", f";Z:{z:.1f}", ";HEIGHT:0.2", ";BEFORE_LAYER_CHANGE", "G92 E0", f";{z:.1f}", "", ""]
        lines += [f"G1 Z{z:.1f} F720", ";AFTER_LAYER_CHANGE", f";{z:.1f}", f"M73 P{layer * 20} R1"]
        lines += [";TYPE:External perimeter", ";WIDTH:0.45"]
        lines += [
            "G1 X100 Y100 F7200",
            "G1 X110 Y100 E.4521 F1500",
            "G1 X110 Y110 E.4521",
            "G1 X100 Y110 E.4521",
            "G1 X100 Y100 E.4521",
        ]
        lines += [";TYPE:Solid infill", "G1 X101 Y101 F7200", "G1 X109 Y109 E.5012 F2400"]
    lines += [
        ";TYPE:Custom",
        "; Filament-specific end gcode",
        "G1 Z3 F720 ; Move print head up",
        "M104 S0 ; turn off temperature",
        "M140 S0 ; turn off heatbed",
        "M107 ; turn off fan",
        "M84 X Y E ; disable motors",
        "M73 P100 R0",
        "",
        "; filament used [mm] = 12.04",
        "; filament used [cm3] = 0.03",
        "; filament used [g] = 0.04",
        "; filament cost = 0.00",
        "; total filament used [g] = 0.04",
        "; total filament cost = 0.00",
        "; estimated printing time (normal mode) = 1m 7s",
        "; estimated first layer printing time (normal mode) = 14s",
        "",
        "; prusaslicer_config = begin",
        "; bed_temperature = 60",
        "; brim_width = 0",
        '; extruder_colour = ""',
        "; fill_density = 15%",
        "; filament_type = PLA",
        "; first_layer_bed_temperature = 60",
        "; first_layer_temperature = 215",
        "; layer_height = 0.2",
        "; nozzle_diameter = 0.4",
        "; printer_model = MK4S",
        "; support_material = 0",
        "; temperature = 215",
        "; prusaslicer_config = end",
        "",
    ]
    return "\n".join(lines)


VARIANTS = [
    # name, metadata compression, G-code compression, encoding, checksum
    ("plain", "none", "none", "none", "none"),
    ("deflate", "Deflate", "Deflate", "none", "CRC32"),
    ("heatshrink-11", "Heatshrink_11_4", "Heatshrink_11_4", "MeatPack", "CRC32"),
    ("heatshrink-12", "none", "Heatshrink_12_4", "MeatPackComments", "CRC32"),
    ("meatpack", "none", "none", "MeatPack", "none"),
]


def main():
    for d in (SYN, EXT, REF):
        os.makedirs(d, exist_ok=True)
    src = os.path.join(SYN, "prusaslicer.gcode")
    with open(src, "w", newline="\n") as f:
        f.write(source())
    for name, meta, gcode, encoding, checksum in VARIANTS:
        cfg = pybgcode.get_config()
        c = pybgcode.CompressionType
        for field in ("file_metadata", "printer_metadata", "print_metadata", "slicer_metadata"):
            setattr(cfg.compression, field, getattr(c, meta))
        cfg.compression.gcode = getattr(c, gcode)
        cfg.gcode_encoding = getattr(_bgcode.GCodeEncodingType, encoding)
        cfg.checksum = getattr(_bgcode.ChecksumType, checksum)
        out = os.path.join(EXT, f"{name}.bgcode")
        i, o = pybgcode.open(src, "r"), pybgcode.open(out, "wb")
        res = pybgcode.from_ascii_to_binary(i, o, cfg)
        pybgcode.close(o)
        pybgcode.close(i)
        assert res == pybgcode.EResult.Success, (name, res)
        i, o = pybgcode.open(out, "rb"), pybgcode.open(os.path.join(REF, f"{name}.ref.gcode"), "w")
        res = pybgcode.from_binary_to_ascii(i, o, True)
        pybgcode.close(o)
        pybgcode.close(i)
        assert res == pybgcode.EResult.Success, (name, res)
        print(name, os.path.getsize(out))


main()
