; generated by PrusaSlicer 2.8.1 on 2025-03-14 at 09:26:53 UTC


; printer_model = MK4S
; filament_type = PLA
; nozzle_diameter = 0.4
; bed_temperature = 60
; fill_density = 15%
; layer_height = 0.2
; temperature = 215
; max_layer_z = 0.60
; extruder_colour = ""


; thumbnail begin 16x16 136
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAALElEQVR4nGP88OEDAymAiSTVDPTQwI
; LM4apwxKroW8d+OjqJaSRqYBwGaQkAdisIwadpjn0AAAAASUVORK5CYII=
; thumbnail end
;

; thumbnail_QOI begin 12x12 72
; cW9pZgAAAAwAAAAMAwGQiOX++mgxxAXEAsQFxALEBcQCxAXEAsQFxALEBeUAAAAAAAAAAQ==
; thumbnail_QOI end
;

; thumbnail_JPG begin 8x8 864
; /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzOD
; dASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2Nj
; Y2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAIAAgDASIAAhEBAx
; EB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQID
; AAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRk
; dISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2
; t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQ
; AAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEI
; FEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2
; hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU
; 1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDrP9N/tL/p0/4D6fn1oooqUrFSlz
; W0P//Z
; thumbnail_JPG end
;

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm

M73 P0 R1
M201 X4000 Y4000 Z200 E2500 ; sets maximum accelerations, mm/sec^2
M203 X300 Y300 Z40 E100 ; sets maximum feedrates, mm / sec
M107
;TYPE:Custom
M862.3 P "MK4S" ; printer model check
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
G28 ; home all without mesh bed level
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; extruder relative mode
G1 Z.2 F720
G92 E0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;0.2


G1 Z0.2 F720
;AFTER_LAYER_CHANGE
;0.2
M73 P0 R1
;TYPE:External perimeter
;WIDTH:0.45
G1 X100 Y100 F7200
G1 X110 Y100 E.4521 F1500
G1 X110 Y110 E.4521
G1 X100 Y110 E.4521
G1 X100 Y100 E.4521
;TYPE:Solid infill
G1 X101 Y101 F7200
G1 X109 Y109 E.5012 F2400
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;0.4


G1 Z0.4 F720
;AFTER_LAYER_CHANGE
;0.4
M73 P20 R1
;TYPE:External perimeter
;WIDTH:0.45
G1 X100 Y100 F7200
G1 X110 Y100 E.4521 F1500
G1 X110 Y110 E.4521
G1 X100 Y110 E.4521
G1 X100 Y100 E.4521
;TYPE:Solid infill
G1 X101 Y101 F7200
G1 X109 Y109 E.5012 F2400
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;0.6


G1 Z0.6 F720
;AFTER_LAYER_CHANGE
;0.6
M73 P40 R1
;TYPE:External perimeter
;WIDTH:0.45
G1 X100 Y100 F7200
G1 X110 Y100 E.4521 F1500
G1 X110 Y110 E.4521
G1 X100 Y110 E.4521
G1 X100 Y100 E.4521
;TYPE:Solid infill
G1 X101 Y101 F7200
G1 X109 Y109 E.5012 F2400
;TYPE:Custom
; Filament-specific end gcode
G1 Z3 F720 ; Move print head up
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 X Y E ; disable motors
M73 P100 R0

; filament used [mm] = 12.04
; filament used [cm3] = 0.03
; filament used [g] = 0.04
; filament cost = 0.00
; total filament used [g] = 0.04
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 7s
; estimated first layer printing time (normal mode) = 14s

; prusaslicer_config = begin
; bed_temperature = 60
; brim_width = 0
; extruder_colour = ""
; fill_density = 15%
; filament_type = PLA
; first_layer_bed_temperature = 60
; first_layer_temperature = 215
; layer_height = 0.2
; nozzle_diameter = 0.4
; printer_model = MK4S
; support_material = 0
; temperature = 215
; prusaslicer_config = end
