; G-Code generated by Simplify3D(R) Version 4.1.2
; Mar 14, 2025 at 9:26:53 AM
; Settings Summary
;   processName,Process1
;   applyToModels,cube
;   profileName,Generic (modified)
;   profileVersion,2019-05-03 08:00:00
;   baseProfile,
;   printMaterial,PLA
;   printQuality,Medium
;   extruderDiameter,0.4
;   layerHeight,0.2
;   temperatureSetpointTemperatures,205,60
; Build Summary
;   Build time: 0 hours 2 minutes
;   Filament length: 213.4 mm (0.21 m)
;   Plastic volume: 513.27 mm^3 (0.51 cc)
G90
M82
M106 S0
M140 S60
M190 S60
M104 S205 T0
M109 S205 T0
G28 ; home all axes
; process Process1
; layer 1, Z = 0.200
T0
G92 E0.0000
G1 E-1.0000 F1800
; feature outer perimeter
G1 Z0.200 F1002
G1 X100.000 Y100.000 F4800
G1 E0.0000 F540
G1 X110.000 Y100.000 E0.3326 F1200
G1 X110.000 Y110.000 E0.6652
G1 X100.000 Y110.000 E0.9978
G1 X100.000 Y100.000 E1.3304
; layer 2, Z = 0.400
G1 Z0.400 F1002
G1 X110.000 Y100.000 E1.6630 F1200
G1 X110.000 Y110.000 E1.9956
G1 X100.000 Y110.000 E2.3282
G1 X100.000 Y100.000 E2.6608
; layer end
M104 S0 ; turn off extruder
M140 S0 ; turn off bed
M84 ; disable motors
