//! E-book and document containers: Palm databases (MOBI, AZW, PalmDOC),
//! DjVu and Microsoft Reader.

use crate::bytes::{u16_be, u32_be};
use crate::cx::Cx;
use crate::declare_format;
use crate::dsl::{Cursor, Record, read_record};
use crate::error::{Diagnostic, Result};
use crate::fields::{Endian, Fields};
use crate::formats::{Head, Input, Probe, embedded};
use crate::node::{Count, Node};
use crate::record;
use crate::span::Span;
use crate::value::{EnumTable, Value, lookup};

const BE: Endian = Endian::Big;

// ---------------------------------------------------------------------------
// Palm database (PDB/PRC) and MOBI

/// Known (type, creator) pairs at offset 60.
const PALM_KINDS: &[(&[u8; 8], &str)] = &[
    (b"BOOKMOBI", "Mobipocket e-book"),
    (b"TEXtREAd", "PalmDOC e-book"),
    (b"PNRdPPrs", "eReader e-book"),
    (b"DataPlkr", "Plucker document"),
    (b"ToGoToGo", "iSilo document"),
    (b"SDocSilX", "iSilo 3 document"),
    (b"BVokBDIC", "BDicty dictionary"),
    (b"DB99DBOS", "DB database"),
    (b"JbDbJBas", "JFile database"),
];

fn palm_kind(h: &Head<'_>) -> Option<&'static str> {
    let tag = h.data.get(60..68)?;
    PALM_KINDS
        .iter()
        .find(|(t, _)| tag == &t[..])
        .map(|(_, n)| *n)
}

fn mobi_probe(h: &Head<'_>) -> bool {
    h.at(60, b"BOOKMOBI")
}

fn palmdoc_probe(h: &Head<'_>) -> bool {
    h.at(60, b"TEXtREAd")
}

/// A generic Palm database: a 78-byte header and a record list whose
/// offsets are increasing and within the file.
fn pdb_probe(h: &Head<'_>) -> bool {
    let d = h.data;
    let records = u16_be(d, 76).unwrap_or(0);
    let name_ok = d.get(..32).is_some_and(|n| {
        n.iter()
            .take_while(|&&b| b != 0)
            .all(|&b| (0x20..0x7f).contains(&b))
            && n.first().is_some_and(|&b| b != 0)
    });
    let type_ok = d
        .get(60..68)
        .is_some_and(|t| t.iter().all(|&b| (0x20..0x7f).contains(&b)));
    let first = u32_be(d, 78).unwrap_or(0);
    name_ok
        && type_ok
        && records > 0
        && u64::from(first) >= 78u64.saturating_add(u64::from(records).saturating_mul(8))
        && u64::from(first) < h.len
        && (palm_kind(h).is_some()
            || h.data
                .get(60..64)
                .is_some_and(|t| t.iter().all(u8::is_ascii_alphanumeric)))
}

declare_format!(pub MOBI = "mobi", "Mobipocket / Kindle e-book", ["mobi", "azw", "azw3", "prc"], "application/x-mobipocket-ebook",
    Probe::Custom(mobi_probe), palm);
declare_format!(pub PALMDOC = "palmdoc", "PalmDOC e-book", ["pdb", "prc"], "application/vnd.palm",
    Probe::Custom(palmdoc_probe), palm);
declare_format!(pub PDB = "palm-pdb", "Palm database", ["pdb", "prc"], "application/vnd.palm",
    Probe::Custom(pdb_probe), palm);

record! {
    pub struct PalmHeader {
        name: ascii[32] "Name",
        attributes: u16 "Attributes" .hex(),
        version: u16 "Version",
        created: u32 "Creation date" .mac_time(),
        modified: u32 "Modification date" .mac_time(),
        backed_up: u32 "Last backup date" .mac_time(),
        modification: u32 "Modification number",
        app_info: u32 "App info offset" .hex(),
        sort_info: u32 "Sort info offset" .hex(),
        kind: ascii[4] "Type",
        creator: ascii[4] "Creator",
        seed: u32 "Unique ID seed",
        next_list: u32 "Next record list",
        records: u16 "Number of records",
    }
}

const PALMDOC_COMPRESSION: EnumTable = &[(1, "none"), (2, "PalmDOC (LZ77)"), (17480, "HUFF/CDIC")];

const MOBI_TYPES: EnumTable = &[
    (2, "Mobipocket book"),
    (3, "PalmDOC book"),
    (4, "Audio"),
    (232, "mobipocket? generated by kindlegen1.2"),
    (248, "KF8: generated by kindlegen2"),
    (257, "News"),
    (258, "News feed"),
    (259, "News magazine"),
    (513, "PICS"),
    (514, "WORD"),
    (515, "XLS"),
    (516, "PPT"),
    (517, "TEXT"),
    (518, "HTML"),
];

const EXTH: EnumTable = &[
    (100, "Author"),
    (101, "Publisher"),
    (103, "Description"),
    (104, "ISBN"),
    (105, "Subject"),
    (106, "Published"),
    (108, "Contributor"),
    (109, "Rights"),
    (112, "Source"),
    (113, "ASIN"),
    (114, "Version"),
    (121, "KF8 boundary offset"),
    (125, "Resource count"),
    (129, "KF8 cover URI"),
    (201, "Cover offset"),
    (202, "Thumbnail offset"),
    (203, "Has fake cover"),
    (204, "Creator software"),
    (205, "Creator major version"),
    (206, "Creator minor version"),
    (207, "Creator build number"),
    (501, "CDE type"),
    (503, "Updated title"),
    (504, "ASIN"),
    (524, "Language"),
    (525, "Writing mode"),
];

async fn palm(cx: Cx, input: Input) -> Result<()> {
    let file = input.span;
    let h: PalmHeader = read_record(&cx, file.sub(0, PalmHeader::SIZE), BE).await?;
    cx.emit(PalmHeader::node(
        "Database header",
        file.sub(0, PalmHeader::SIZE),
        BE,
    ));
    let list = file.sub_exact(PalmHeader::SIZE, u64::from(h.records).saturating_mul(8))?;
    let entries = cx.read(list).await?;
    let offsets: Vec<u64> = (0..usize::from(h.records))
        .map(|i| u64::from(u32_be(&entries, i.saturating_mul(8)).unwrap_or(0)))
        .collect();
    cx.emit(
        Node::new("Records")
            .span(list)
            .summary(format!("{} records", h.records))
            .lazy(palm_records, (input, offsets.clone())),
    );
    let tag = format!("{}{}", h.kind, h.creator);
    let kind = PALM_KINDS
        .iter()
        .find(|(t, _)| t.starts_with(tag.as_bytes()))
        .map_or("Palm database", |(_, n)| n);
    let mut summary = format!("{kind}: {:?}", h.name);
    // Record 0 of PalmDOC/MOBI books holds the PalmDOC (and MOBI) header.
    if (tag == "BOOKMOBI" || tag == "TEXtREAd")
        && let (Some(&start), Some(&end)) = (offsets.first(), offsets.get(1).or(Some(&file.len)))
    {
        let record0 = file.sub(start, end.saturating_sub(start));
        let mut node = Node::new("Book header")
            .span(record0)
            .lazy(book_header_node, record0);
        if let Some(title) = mobi_title(&cx, record0).await? {
            summary = format!("{kind}: {title:?}");
            node = node.summary(title);
        }
        cx.emit(node);
    }
    cx.annotate(summary);
    Ok(())
}

async fn palm_records(cx: Cx, (input, offsets): (Input, Vec<u64>)) -> Result<()> {
    cx.set_count(Count::Exact(crate::bytes::to_u64(offsets.len())));
    for (i, &start) in offsets.iter().enumerate() {
        let end = offsets
            .get(i.saturating_add(1))
            .copied()
            .unwrap_or(input.span.len);
        if end < start {
            cx.push(
                Node::new(format!("Record {i}"))
                    .diag(Diagnostic::malformed("record offsets out of order")),
            )
            .await;
            continue;
        }
        let span = input.span.sub(start, end.saturating_sub(start));
        cx.push(
            embedded(format!("Record {i}"), input.nested(span))
                .summary(format!("{} bytes", span.len)),
        )
        .await;
    }
    Ok(())
}

/// The full title from the MOBI header of record 0, if there is one.
async fn mobi_title(cx: &Cx, record0: Span) -> Result<Option<String>> {
    let mobi = cx.read_avail(record0.sub(16, 0x4c)).await?;
    if !mobi.starts_with(b"MOBI") {
        return Ok(None);
    }
    let offset = u64::from(u32_be(&mobi, 0x44).unwrap_or(0));
    let len = u64::from(u32_be(&mobi, 0x48).unwrap_or(0));
    let title = cx.read_avail(record0.sub(offset, len.min(1024))).await?;
    Ok(Some(String::from_utf8_lossy(&title).into_owned()))
}

async fn book_header_node(cx: Cx, record0: Span) -> Result<()> {
    book_header(&cx, record0).await.map(|_| ())
}

/// Emits the PalmDOC header, the MOBI header and EXTH metadata of record 0.
/// Returns the full title if present.
async fn book_header(cx: &Cx, record0: Span) -> Result<Option<String>> {
    let block = cx.block(record0.sub(0, 16)).await?;
    {
        let mut f = Fields::emitting(cx, &block, BE);
        // Not lazy: these few fields are the book's identity.
        f.u16("Compression")
            .enumeration(PALMDOC_COMPRESSION)
            .emit()?;
        f.u16("Unused").emit()?;
        f.u32("Text length").emit()?;
        f.u16("Text record count").emit()?;
        f.u16("Text record size").emit()?;
        f.u16("Encryption")
            .enumeration(&[(0, "none"), (1, "old Mobipocket"), (2, "Mobipocket")])
            .emit()?;
        f.u16("Unknown").emit()?;
    }
    let mobi = cx.read_avail(record0.sub(16, 0x100)).await?;
    if !mobi.starts_with(b"MOBI") {
        return Ok(None);
    }
    let header_len = u64::from(u32_be(&mobi, 4).unwrap_or(0));
    let mobi_span = record0.sub(16, header_len);
    let kind = u32_be(&mobi, 8).unwrap_or(0);
    let encoding = u32_be(&mobi, 12).unwrap_or(0);
    let version = u32_be(&mobi, 0x14).unwrap_or(0);
    let title_offset = u64::from(u32_be(&mobi, 0x44).unwrap_or(0));
    let title_len = u64::from(u32_be(&mobi, 0x48).unwrap_or(0));
    let exth_flags = u32_be(&mobi, 0x70).unwrap_or(0);
    cx.emit(Node::new("MOBI header").span(mobi_span).summary(format!(
        "{}, version {version}, {}",
        lookup(MOBI_TYPES, kind.into()).unwrap_or("unknown type"),
        match encoding {
            65001 => "UTF-8",
            1252 => "CP1252",
            _ => "unknown encoding",
        }
    )));
    if exth_flags & 0x40 != 0 {
        let exth = record0.tail(16u64.saturating_add(header_len));
        cx.emit(
            Node::new("EXTH metadata")
                .span(exth)
                .lazy(exth_records, exth),
        );
    }
    let title_span = record0.sub(title_offset, title_len);
    let title = String::from_utf8_lossy(&cx.read_avail(title_span).await?).into_owned();
    cx.emit(
        Node::new("Full name")
            .span(title_span)
            .value(Value::Text(title.clone())),
    );
    Ok(Some(title))
}

async fn exth_records(cx: Cx, span: Span) -> Result<()> {
    let mut cur = Cursor::new(&cx, span, BE);
    let magic = cur.bytes(4).await?;
    if magic != b"EXTH" {
        return Err(Diagnostic::malformed("missing EXTH magic").at(span.sub(0, 4)));
    }
    let _len = cur.u32().await?;
    let count = cur.u32().await?;
    cx.set_count(Count::Exact(count.into()));
    for _ in 0..count {
        let start = cur.pos();
        let kind = cur.u32().await?;
        let len = cur.u32().await?;
        let data_len = u64::from(len.saturating_sub(8));
        let data = cur.bytes(data_len).await?;
        let name = lookup(EXTH, kind.into()).map_or_else(|| format!("EXTH {kind}"), str::to_owned);
        let value = if data_len == 4 && kind >= 115 && kind != 503 && kind != 524 {
            Value::UInt {
                value: u32_be(&data, 0).unwrap_or(0).into(),
                bits: 32,
                radix: crate::value::Radix::Dec,
            }
        } else {
            Value::Text(String::from_utf8_lossy(&data).into_owned())
        };
        cx.push(Node::new(name).span(cur.since(start)).value(value))
            .await;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// DjVu

declare_format!(pub DJVU = "djvu", "DjVu document", ["djvu", "djv"], "image/vnd.djvu",
    Probe::Magic(&[(0, b"AT&TFORM")]), djvu);

async fn djvu(cx: Cx, input: Input) -> Result<()> {
    let file = input.span;
    cx.emit(Node::new("Magic").span(file.sub(0, 4)));
    let head = cx.read(file.sub(4, 12)).await?;
    let form = String::from_utf8_lossy(head.get(8..12).unwrap_or_default()).into_owned();
    let kind = match form.as_str() {
        "DJVU" => "single-page DjVu",
        "DJVM" => "multi-page DjVu",
        "DJVI" => "shared DjVu data",
        "THUM" => "DjVu thumbnails",
        _ => "DjVu",
    };
    let mut summary = kind.to_owned();
    if form == "DJVU" {
        let info = cx.read_avail(file.sub(16, 18)).await?;
        if info.starts_with(b"INFO") {
            summary = format!(
                "{kind}, {}×{}, {} dpi",
                u16_be(&info, 8).unwrap_or(0),
                u16_be(&info, 10).unwrap_or(0),
                crate::bytes::u16_le(&info, 14).unwrap_or(0)
            );
        }
    }
    cx.annotate(summary);
    djvu_chunks(cx, (input, file.tail(4))).await
}

const DJVU_CHUNKS: &[(&str, &str)] = &[
    ("FORM", "Composite chunk"),
    ("DIRM", "Multi-page directory"),
    ("NAVM", "Bookmarks"),
    ("INFO", "Page information"),
    ("INCL", "Included shared data"),
    ("Sjbz", "JB2 bitonal mask"),
    ("Smmr", "G4 bitonal mask"),
    ("BG44", "IW44 background"),
    ("FG44", "IW44 foreground"),
    ("FGbz", "Foreground colors"),
    ("TXTa", "Hidden text"),
    ("TXTz", "Hidden text (compressed)"),
    ("ANTa", "Annotations"),
    ("ANTz", "Annotations (compressed)"),
    ("Djbz", "Shared shape dictionary"),
    ("TH44", "Thumbnail"),
];

async fn djvu_chunks(cx: Cx, (input, span): (Input, Span)) -> Result<()> {
    let mut cur = Cursor::new(&cx, span, BE);
    while cur.remaining() >= 8 {
        let start = cur.pos();
        let id = String::from_utf8_lossy(&cur.bytes(4).await?).into_owned();
        let len = cur.u32().await?;
        let body = cur.span(len.into());
        cur.skip(u64::from(len).saturating_add(u64::from(len & 1)));
        let label = DJVU_CHUNKS
            .iter()
            .find(|(k, _)| *k == id)
            .map_or("", |(_, n)| n);
        let mut node = Node::new(id.clone())
            .span(cur.since(start))
            .summary(format!("{label}, {len} bytes"));
        if id == "FORM" {
            let kind = String::from_utf8_lossy(&cx.read_avail(body.sub(0, 4)).await?).into_owned();
            node = node.summary(format!("FORM:{kind}, {len} bytes")).lazy(
                crate::expander!(self::djvu_chunks: (Input, Span)),
                (input, body.tail(4)),
            );
        } else if id == "INFO" {
            let info = cx.read_avail(body.sub(0, 10)).await?;
            node = node.summary(format!(
                "{}×{} pixels, {} dpi",
                u16_be(&info, 0).unwrap_or(0),
                u16_be(&info, 2).unwrap_or(0),
                crate::bytes::u16_le(&info, 6).unwrap_or(0)
            ));
        }
        cx.push(node).await;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Microsoft Reader (LIT)

declare_format!(pub LIT = "lit", "Microsoft Reader e-book", ["lit"], "application/x-ms-reader",
    Probe::Magic(&[(0, b"ITOLITLS")]), lit);

record! {
    pub struct LitHeader {
        magic: ascii[8] "Magic",
        version: u32 "Version",
        header_len: u32 "Header length" .hex(),
        pieces: u32 "Number of pieces",
        secondary_len: u32 "Secondary header length" .hex(),
        guid: guid "Header GUID",
    }
}

async fn lit(cx: Cx, input: Input) -> Result<()> {
    let file = input.span;
    let h: LitHeader = read_record(
        &cx,
        file.sub(0, LitHeader::SIZE),
        crate::fields::Endian::Little,
    )
    .await?;
    cx.emit(LitHeader::node(
        "Header",
        file.sub(0, LitHeader::SIZE),
        crate::fields::Endian::Little,
    ));
    let table = file.sub(h.header_len.into(), u64::from(h.pieces).saturating_mul(16));
    let entries = cx.read_avail(table).await?;
    for i in 0..usize::try_from(h.pieces.min(64)).unwrap_or(0) {
        let at = i.saturating_mul(16);
        let offset = crate::bytes::u64_le(&entries, at).unwrap_or(0);
        let size = crate::bytes::u64_le(&entries, at.saturating_add(8)).unwrap_or(0);
        cx.push(
            Node::new(format!("Piece {i}"))
                .span(file.sub(offset, size))
                .summary(format!("{size} bytes")),
        )
        .await;
    }
    cx.annotate(format!(
        "Microsoft Reader, version {}, {} pieces",
        h.version, h.pieces
    ));
    Ok(())
}
