//! Format identification and the dissectors themselves.
//!
//! Every format is a [`Format`] entry in [`FORMATS`]: a name, a probe that
//! recognises it from the first and last bytes of the input, and an entry
//! point. Adding a format means adding a module and one line to the registry.

use std::borrow::Cow;

use crate::cx::Cx;
use crate::error::{Diagnostic, Result};
use crate::node::{Expansion, Node};
use crate::span::Span;

// Modules, grouped by theme; each family's `mod.rs` summarises what it
// holds. Keep each group sorted.

// -- shared helpers --
pub mod util;

// -- archives, compression & disk images --
pub mod archive;
pub mod compression;
pub mod disk;

// -- executables & code --
pub mod android;
pub mod bytecode;
pub mod executable;
pub mod java;

// -- images, fonts & publishing --
pub mod font;
pub mod image;
pub mod publishing;

// -- audio & video --
pub mod audio;
pub mod iff;
pub mod isobmff;
pub mod mpeg;
pub mod tracker;
pub mod video;

// -- documents, data & text --
pub mod asn1;
pub mod cfb;
pub mod data;
pub mod documents;
pub mod pdf;
pub mod sqlite;
pub mod text;

// -- system, security & forensics --
pub mod forensics;
pub mod mobile;
pub mod pcap;
pub mod security;
pub mod system;

// -- games & retro --
pub mod games;
pub mod retro;

// -- science, engineering, geospatial & machine learning --
pub mod engineering;
pub mod geo;
pub mod ml;
pub mod science;

/// How many leading bytes probes see. Large enough for magic numbers deep in
/// a file, such as ISO 9660's volume descriptor at 0x8001 and the btrfs and
/// UFS2 superblocks at 64 KiB.
pub const HEAD_LEN: u64 = 0x10800;
/// How many trailing bytes probes see.
pub const TAIL_LEN: u64 = 0x400;

/// The region a format dissector works on, plus how deeply it is embedded.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Input {
    pub span: Span,
    pub nesting: u32,
    /// The region this input is embedded in (itself, for the root).
    pub outer: Span,
}

impl Input {
    pub fn root(span: Span) -> Self {
        Input {
            span,
            nesting: 0,
            outer: span,
        }
    }

    /// An input embedded in this one.
    pub fn nested(&self, span: Span) -> Self {
        Input {
            span,
            nesting: self.nesting.saturating_add(1),
            outer: self.span,
        }
    }
}

/// What a probe sees of an input.
pub struct Head<'a> {
    /// The first [`HEAD_LEN`] bytes (fewer if the input is shorter).
    pub data: &'a [u8],
    /// The last [`TAIL_LEN`] bytes (may overlap `data`).
    pub tail: &'a [u8],
    /// Length of the whole input.
    pub len: u64,
}

impl Head<'_> {
    /// Whether `magic` occurs at `offset`.
    pub fn at(&self, offset: usize, magic: &[u8]) -> bool {
        offset
            .checked_add(magic.len())
            .and_then(|end| self.data.get(offset..end))
            .is_some_and(|b| b == magic)
    }

    pub fn starts_with(&self, magic: &[u8]) -> bool {
        self.data.starts_with(magic)
    }
}

pub enum Probe {
    /// Any of these `(offset, bytes)` pairs matches.
    Magic(&'static [(usize, &'static [u8])]),
    Custom(fn(&Head<'_>) -> bool),
}

impl Probe {
    fn matches(&self, head: &Head<'_>) -> bool {
        match self {
            Probe::Magic(list) => list.iter().any(|(offset, magic)| head.at(*offset, magic)),
            Probe::Custom(f) => f(head),
        }
    }
}

/// A registered file format.
pub struct Format {
    /// Short identifier, e.g. `"png"`.
    pub name: &'static str,
    /// Human-readable name, e.g. `"Portable Network Graphics"`.
    pub title: &'static str,
    pub extensions: &'static [&'static str],
    pub mime: &'static str,
    pub probe: Probe,
    pub dissect: fn(Cx, Input) -> Expansion,
}

/// All formats, in probing order: specific before generic.
pub static FORMATS: &[&Format] = &[
    // -- executables & code --
    &executable::pe::DOS_EXE,
    &executable::pe::FORMAT,
    &archive::packaging::APPIMAGE,
    &executable::elf::FORMAT,
    &executable::macho::FORMAT,
    &executable::macho::fat::FORMAT,
    &executable::macho::dyld_cache::FORMAT,
    // After the universal binary probe, which shares the 0xcafebabe magic.
    &java::class::FORMAT,
    &java::serialization::FORMAT,
    &java::keystore::FORMAT,
    &bytecode::wasm::FORMAT,
    &android::dex::FORMAT,
    &android::dex::ODEX,
    &android::resources::AXML,
    &android::resources::ARSC,
    &android::vdex::FORMAT,
    &android::art::FORMAT,
    &forensics::minidump::FORMAT,
    &executable::ne::FORMAT,
    &executable::lx::FORMAT,
    &executable::omf::FORMAT,
    &executable::dcu::FORMAT,
    &bytecode::qvm::FORMAT,
    &executable::fatbin::FORMAT,
    &bytecode::elc::FORMAT,
    &bytecode::il2cpp::FORMAT,
    &bytecode::opcache::FORMAT,
    &bytecode::spirv::FORMAT,
    &bytecode::dxbc::FORMAT,
    &executable::te::FORMAT,
    &executable::xcoff::FORMAT,
    &executable::pef::FORMAT,
    &bytecode::ocaml::FORMAT,
    &bytecode::hermes::FORMAT,
    &bytecode::dart::FORMAT,
    &bytecode::yarb::FORMAT,
    &bytecode::pyc::FORMAT,
    &bytecode::lua::FORMAT,
    &bytecode::luajit::FORMAT,
    &bytecode::bitcode::FORMAT,
    &bytecode::beam::FORMAT,
    // Weaker probes (sizes and machine numbers rather than long magics).
    &executable::coff::FORMAT,
    &executable::coff::IMPORT,
    &executable::aout::PLAN9,
    &executable::aout::FORMAT,
    // -- end executables --

    // -- images --
    &image::png::FORMAT,
    &image::png::MNG,
    &image::png::JNG,
    &image::bmp::FORMAT,
    &image::gif::FORMAT,
    &image::jpeg::FORMAT,
    &image::psd::FORMAT,
    &image::ico::ICO,
    &image::ico::CUR,
    &image::qoi::FORMAT,
    &image::dds::FORMAT,
    &image::ktx::KTX,
    &image::ktx::KTX2,
    &image::exr::FORMAT,
    &image::xcf::FORMAT,
    &image::icns::FORMAT,
    &image::j2k::FORMAT,
    &image::jxl::FORMAT,
    &image::pcx::DCX,
    &image::farbfeld::FORMAT,
    &image::sunras::FORMAT,
    &image::sgi::FORMAT,
    &image::hdr::FORMAT,
    &image::xbm::XPM,
    &image::xbm::XBM,
    &image::pnm::PBM,
    &image::pnm::PGM,
    &image::pnm::PPM,
    &image::pnm::PAM,
    &image::pnm::PFM,
    // TIFF-based camera raw formats before plain TIFF.
    &image::tiff::DNG,
    &image::tiff::CR2,
    &image::tiff::NEF,
    &image::tiff::ARW,
    &image::tiff::PEF,
    &image::tiff::SRW,
    &image::tiff::ORF,
    &image::tiff::RW2,
    &image::raw::RAF,
    &image::raw::MRW,
    &image::crw::FORMAT,
    &image::jbig2::FORMAT,
    &image::tiff::FORMAT,
    // Weak probes (footer, header sanity checks) last.
    &image::xwd::FORMAT,
    &image::tga::FORMAT,
    &image::pcx::FORMAT,
    &image::wbmp::FORMAT,
    // Also implemented in src/formats/image/ but not registered, because main
    // has its own versions (image/graphics.rs, science/imaging.rs,
    // image/icc_profile.rs): fits, dpx, cineon, astc, pvr, vtf, emf, wmf, bpg,
    // flif, jxr, icc. Swap in whichever is deeper.
    // -- end images --

    // -- audio & video --
    // audio (riff/iff/flac/mp3/ogg/...)
    &iff::WAV,
    &iff::AVI,
    &iff::WEBP,
    &iff::ANI,
    &iff::RMI,
    &iff::DLS,
    &iff::SF2,
    &iff::XWMA,
    &iff::CDXA,
    &iff::RIFF_PALETTE,
    &iff::RDIB,
    &iff::RMMP,
    &iff::QCP,
    &iff::CDR,
    &iff::FOURXM,
    &iff::AMV,
    &iff::AIFF,
    &iff::AIFC,
    &iff::SVX8,
    &iff::SVX16,
    &iff::ILBM,
    &iff::ANIM,
    &iff::SMUS,
    &iff::FTXT,
    &iff::MAUD,
    // RIFF/RIFX forms from the publishing family, before generic RIFF.
    &publishing::authoring::DIRECTOR,
    &publishing::authoring::AEP,
    &publishing::authoring::CMX,
    &iff::RIFF,
    // IFF-shaped formats with their own dissectors, before generic IFF.
    &audio::production::REX2,
    &iff::IFF,
    &audio::midi::FORMAT,
    &audio::au::FORMAT,
    &audio::voc::FORMAT,
    &audio::caf::FORMAT,
    &audio::amr::FORMAT,
    &audio::w64::FORMAT,
    &audio::ape::FORMAT,
    &audio::wavpack::FORMAT,
    &audio::musepack::FORMAT,
    &audio::tta::FORMAT,
    &audio::lossless::TAK,
    &audio::lossless::OFR,
    &audio::lossless::SHORTEN,
    &audio::dsd::DSF,
    &audio::dsd::DFF,
    &audio::smaf::FORMAT,
    &audio::simple_audio::SOX,
    &audio::simple_audio::IRCAM,
    &audio::simple_audio::ADX,
    &audio::simple_audio::KVAG,
    &audio::simple_audio::AST,
    &audio::simple_audio::ILBC,
    &audio::simple_audio::QOA,
    &tracker::it::FORMAT,
    &tracker::xm::FORMAT,
    &tracker::s3m::FORMAT,
    &tracker::more::MTM,
    &tracker::more::STM,
    &tracker::more::ULT,
    &tracker::more::MED,
    &tracker::more::OKT,
    &tracker::protracker::FORMAT,
    &tracker::more::COMPOSER669,
    &audio::simple_audio::RSO,
    &audio::flac::FORMAT,
    &audio::ogg::OPUS,
    &audio::ogg::OGG_FLAC,
    &audio::ogg::SPEEX,
    &audio::ogg::THEORA,
    &audio::ogg::FORMAT,
    &audio::adts::FORMAT,
    &audio::ac3::FORMAT,
    &audio::dts::FORMAT,
    &audio::mpa::FORMAT,
    &audio::id3::FORMAT,
    // video & containers (isobmff/matroska/ts/...)
    &isobmff::CR3,
    &isobmff::HEIF,
    &isobmff::AVIF,
    &isobmff::JP2,
    &isobmff::JPX,
    &isobmff::MJ2,
    &isobmff::THREE_GP,
    &isobmff::THREE_G2,
    &isobmff::M4A,
    &isobmff::M4V,
    &isobmff::MOV,
    &isobmff::MP4,
    &video::matroska::WEBM,
    &video::matroska::MKV,
    &video::flv::FORMAT,
    &mpeg::ts::M2TS,
    &mpeg::ts::FORMAT,
    &mpeg::ps::MPEG2_PS,
    &mpeg::ps::MPEG1_SYSTEM,
    &mpeg::video::MPEG2_VIDEO,
    &mpeg::video::MPEG1_VIDEO,
    &mpeg::mpeg4::FORMAT,
    &video::annexb::HEVC,
    &video::annexb::H264,
    &video::ivf::FORMAT,
    &video::ivf::OBU,
    &video::y4m::FORMAT,
    &video::asf::WMV,
    &video::asf::WMA,
    &video::asf::ASF,
    &video::realmedia::FORMAT,
    &video::rad::BINK,
    &video::rad::SMACKER,
    &video::mxf::FORMAT,
    &video::swf::FORMAT,
    &video::gamevideo::ROQ,
    &video::gamevideo::FILM,
    &video::gamevideo::SMJPEG,
    &video::gamevideo::FLIC,
    &video::gamevideo::MVE,
    &video::gamevideo::THP,
    &video::rawvideo::DIRAC,
    &video::rawvideo::DNXHD,
    &video::rawvideo::H263,
    // -- end audio & video --

    // -- documents & data --
    // data, system artifacts, fonts
    &data::bplist::FORMAT,
    &data::bencode::FORMAT,
    &data::cbor::FORMAT,
    &pcap::FORMAT,
    &pcap::ng::FORMAT,
    &forensics::lnk::FORMAT,
    &forensics::regf::FORMAT,
    &forensics::evtx::FORMAT,
    &forensics::evt::FORMAT,
    &forensics::prefetch::FORMAT,
    &forensics::recyclebin::FORMAT,
    &forensics::thumbcache::FORMAT,
    &forensics::thumbcache::INDEX,
    &image::icc_profile::FORMAT,
    &font::SFNT,
    &font::TTC,
    &font::woff::WOFF,
    &font::woff::WOFF2,
    &font::eot::FORMAT,
    &font::pfb::FORMAT,
    &font::bitmap::PCF,
    &font::bitmap::BDF,
    &system::mo::FORMAT,
    &system::terminfo::FORMAT,
    &data::npy::NPY,
    &data::npy::SAFETENSORS,
    &archive::crx::CRX,
    &archive::crx::MOZLZ4,
    &archive::applesingle::APPLESINGLE,
    &archive::applesingle::APPLEDOUBLE,
    &ml::gguf::FORMAT,
    &data::pickle::FORMAT,
    &system::git::PACK,
    &system::git::PACK_INDEX,
    &system::git::INDEX,
    &documents::chm::FORMAT,
    &documents::winhelp::FORMAT,
    &forensics::dsstore::FORMAT,
    &forensics::bookmark::FORMAT,
    // graph-shaped: sqlite/cfb/pdf/asn1/pgp/...
    &sqlite::GEOPACKAGE,
    &sqlite::MBTILES,
    &sqlite::FORMAT,
    &sqlite::WAL,
    &sqlite::JOURNAL,
    &cfb::DOC,
    &cfb::XLS,
    &cfb::PPT,
    &cfb::MSG,
    &cfb::MSI,
    &cfb::THUMBS,
    &cfb::PUBLISHER,
    &cfb::FORMAT,
    &pdf::FORMAT,
    &asn1::X509,
    &asn1::CRL,
    &asn1::CSR,
    &asn1::PKCS7,
    &asn1::PKCS12,
    &asn1::PKCS8_ENCRYPTED,
    &asn1::DER,
    &security::pgp::FORMAT,
    &security::pgp::ARMOR,
    &security::pem::FORMAT,
    &data::avro::FORMAT,
    &data::netcdf::FORMAT,
    &data::hdf5::MAT73,
    &data::hdf5::FORMAT,
    &data::matlab::FORMAT,
    &data::parquet::FORMAT,
    &data::orc::FORMAT,
    &data::sst::LEVELDB,
    &data::sst::ROCKSDB,
    &data::bdb::FORMAT,
    &data::jet::MDB,
    &data::jet::ACCDB,
    &data::arrow::FORMAT,
    // -- end documents --

    // -- disk images & filesystems --
    // Virtual disk containers first: their payload may start with an MBR.
    &disk::vhd::FORMAT,
    &disk::vhdx::FORMAT,
    &disk::qcow::FORMAT,
    &disk::vmdk::FORMAT,
    &disk::vmdk::DESCRIPTOR,
    &disk::vdi::FORMAT,
    &disk::parallels::FORMAT,
    // Partition tables and volumes with distinctive signatures.
    &disk::gpt::FORMAT,
    &disk::bitlocker::FORMAT,
    &disk::luks::FORMAT,
    &disk::lvm::FORMAT,
    &disk::mdraid::FORMAT,
    &disk::swap::FORMAT,
    &disk::xfs::FORMAT,
    &disk::apm::FORMAT,
    &disk::uefi::FORMAT,
    &disk::zfs::FORMAT,
    &disk::hfs::FORMAT,
    &disk::apfs::FORMAT,
    &disk::ext::FORMAT,
    &disk::minix::FORMAT,
    &disk::bfs::FORMAT,
    &disk::f2fs::FORMAT,
    &disk::erofs::FORMAT,
    &disk::jfs::FORMAT,
    &disk::nilfs::FORMAT,
    &disk::ufs::FORMAT,
    // Boot sectors ending in 0x55AA, before the plain MBR.
    &disk::ntfs::FORMAT,
    &disk::exfat::FORMAT,
    &disk::fat::FORMAT,
    &disk::mbr::FORMAT,
    &disk::bsdlabel::FORMAT,
    // Detected only if the probe window reaches 64 KiB.
    &disk::btrfs::FORMAT,
    // -- end disk images --

    // -- archives & compression --
    // BGZF (blocked gzip) members are gzip members; identify them first.
    &science::bio::binary::BAM,
    &science::bio::binary::BCF,
    &science::bio::binary::VCF_BGZF,
    &science::bio::binary::TABIX,
    &science::bio::binary::CSI,
    &science::bio::binary::BGZF,
    &compression::gzip::FORMAT,
    &disk::dmg::FORMAT,
    &archive::tar::FORMAT,
    &compression::bzip2::FORMAT,
    &compression::xz::FORMAT,
    &compression::lzma::LZIP,
    &compression::zstd::FORMAT,
    &compression::zstd::SKIPPABLE,
    &compression::lz4::FORMAT,
    &compression::lz4::LEGACY,
    &compression::lz4::SNAPPY,
    &compression::compress::COMPRESS,
    &compression::compress::PACK,
    &compression::szdd::SZDD,
    &compression::szdd::KWAJ,
    &archive::ar::DEB,
    &archive::ar::FORMAT,
    &archive::cpio::FORMAT,
    &archive::rpm::FORMAT,
    &archive::sevenzip::FORMAT,
    &archive::rar::FORMAT,
    &archive::cab::FORMAT,
    &archive::arj::FORMAT,
    &archive::xar::FORMAT,
    &disk::iso9660::FORMAT,
    &disk::iso9660::UDF,
    &system::firmware::ANDROID_SPARSE,
    &system::firmware::ANDROID_BOOT,
    &system::firmware::UIMAGE,
    &disk::squashfs::SQUASHFS,
    &disk::squashfs::CRAMFS,
    &archive::wim::FORMAT,
    &archive::stuffit::FORMAT,
    &archive::stuffit::SIT5,
    &archive::zoo::FORMAT,
    &archive::ace::ACE,
    // ZIP-based formats before plain ZIP (more specific ones first).
    // (ml models & mobile platforms)
    &archive::zip::TORCHSCRIPT,
    &archive::zip::PYTORCH,
    &archive::zip::KERAS,
    &archive::zip::NPZ,
    &archive::zip::SIGROK,
    &archive::zip::APEX,
    &archive::zip::ANDROID_OTA,
    &archive::zip::ANDROID_DM,
    &archive::zip::BUGREPORT,
    &archive::zip::IPSW,
    // (end ml)
    &archive::zip::AAR,
    &archive::zip::XLSB,
    &archive::zip::SNUPKG,
    &archive::zip::EPUB,
    &archive::zip::ODT,
    &archive::zip::ODS,
    &archive::zip::ODP,
    &archive::zip::ODG,
    &archive::zip::DOCX,
    &archive::zip::XLSX,
    &archive::zip::PPTX,
    &archive::zip::VSDX,
    &archive::zip::XPS,
    &archive::zip::APK,
    &archive::zip::XPI,
    &archive::zip::NUPKG,
    &archive::zip::VSIX,
    &archive::zip::WHL,
    &archive::zip::IPA,
    &archive::zip::KMZ,
    &archive::zip::THREE_MF,
    &archive::zip::SKETCH,
    &archive::zip::USDZ,
    &archive::zip::KRITA,
    &archive::zip::ORA,
    &archive::zip::IDML,
    &archive::zip::ODF_FORMULA,
    &archive::zip::ODB,
    &archive::zip::IWORK,
    &archive::zip::APPX,
    &archive::zip::XAP,
    &archive::zip::FBZ,
    &archive::zip::CBZ,
    &archive::zip::GEOGEBRA,
    &archive::zip::DWFX,
    &archive::zip::ADOBE_XD,
    &archive::zip::PROCREATE,
    &archive::zip::XFL,
    &archive::zip::SXW,
    &archive::zip::SXC,
    &archive::zip::SXI,
    &archive::zip::SXD,
    &archive::zip::SXM,
    &archive::zip::CDR_ZIP,
    &archive::zip::IWORK09,
    &archive::zip::MCPACK,
    &archive::zip::SCRATCH,
    &archive::zip::JAR,
    &archive::zip::FORMAT,
    // Weak probes last.
    &archive::tar::V7,
    &archive::lha::FORMAT,
    &archive::ace::ARC,
    &compression::lzma::LZMA,
    &system::hexfile::IHEX,
    &system::hexfile::SREC,
    // -- end archives --

    // -- retro & consoles --
    &retro::consoles::NES,
    &retro::consoles::FDS,
    // GBX footers wrap Game Boy ROMs.
    &retro::extras::GBX,
    &retro::consoles::GBC,
    &retro::consoles::GB,
    &retro::consoles::GBA,
    &retro::consoles::NDS,
    &retro::consoles::N64,
    // Sega disc system areas carry a Mega Drive style header at 0x100.
    &retro::discs::SEGA_CD,
    &retro::discs::SATURN,
    &retro::discs::DREAMCAST,
    &retro::consoles::GENESIS,
    &retro::consoles::PSX_EXE,
    &retro::consoles::PBP,
    &retro::consoles::SFO,
    &retro::consoles::XBE,
    &retro::consoles::WII,
    &retro::consoles::GAMECUBE,
    &retro::consoles::NRO,
    &retro::consoles::NSO,
    &retro::consoles::THREEDSX,
    &retro::consoles::NCSD,
    &retro::consoles::NCCH,
    &retro::consoles::LYNX,
    &retro::consoles::A7800,
    &retro::consoles::SNES,
    &retro::music::NSF,
    &retro::music::NSFE,
    &retro::music::GBS,
    &retro::music::SPC,
    &retro::music::VGM,
    &retro::music::PSF,
    &retro::music::SID,
    &retro::music::HES,
    &retro::music::KSS,
    &retro::music::AY,
    &retro::music::SAP,
    &retro::music::YM,
    &retro::computers::T64,
    &retro::computers::CRT,
    &retro::computers::AMIGA_HUNK,
    &retro::computers::TZX,
    &retro::computers::CPC_DSK,
    &retro::computers::MSA,
    &retro::computers::ATR,
    &retro::computers::WOZ,
    &retro::computers::TWO_IMG,
    &retro::computers::UEF,
    &retro::computers::ADF,
    &retro::computers::D64,
    &retro::patches::IPS,
    &retro::patches::IPS32,
    &retro::patches::UPS,
    &retro::patches::BPS,
    &retro::patches::VCDIFF,
    &retro::patches::BSDIFF,
    &retro::patches::BSDIFF43,
    &retro::patches::PPF,
    &retro::patches::APS_N64,
    &retro::patches::APS_GBA,
    &retro::patches::GDIFF,
    &retro::patches::MSDELTA,
    &retro::patches::RUP,
    &retro::discs::CHD,
    &retro::discs::MDS,
    &retro::discs::CCD,
    &retro::discs::ECM,
    &retro::discs::CSO,
    &retro::discs::DAX,
    &retro::discs::ISZ,
    &retro::discs::DAA,
    &retro::discs::WBFS,
    &retro::discs::GCZ,
    &retro::discs::WIA,
    &retro::discs::RVZ,
    &retro::discs::TGC,
    &retro::discs::WII_CISO,
    &retro::discs::OPERA,
    &retro::cartridges::GAME_GEAR,
    &retro::cartridges::SMS,
    &retro::cartridges::SMD,
    &retro::cartridges::NGPC,
    &retro::cartridges::NGP,
    &retro::cartridges::POKEMON_MINI,
    &retro::cartridges::NEO_GEO,
    &retro::cartridges::UNIF,
    &retro::cartridges::VECTREX,
    &retro::states::ZSNES,
    &retro::states::SNES9X,
    &retro::states::FCEUX,
    &retro::states::RETROARCH,
    &retro::states::DTM,
    &retro::states::SMV,
    &retro::states::VBM,
    &retro::states::FCM,
    &retro::states::M64,
    &retro::states::GMV,
    &retro::states::DEXDRIVE,
    &retro::states::PS2_MEMCARD,
    &retro::states::PSX_MEMCARD,
    &retro::trackers::FAMITRACKER,
    &retro::trackers::FURNACE,
    &retro::trackers::DEFLEMASK,
    &retro::trackers::S98,
    &retro::trackers::GYM,
    &retro::trackers::ORGANYA,
    &retro::trackers::GOATTRACKER,
    &retro::trackers::SNDH,
    &retro::trackers::PT3,
    &retro::trackers::PSG,
    &retro::tapes::PZX,
    &retro::tapes::CSW,
    &retro::tapes::C64_TAP,
    &retro::tapes::G64,
    &retro::tapes::P00,
    &retro::tapes::SCL,
    &retro::tapes::MSX_CAS,
    &retro::tapes::ATARI_CAR,
    &retro::floppies::HFE,
    &retro::floppies::IPF,
    &retro::floppies::STX,
    &retro::floppies::IMD,
    &retro::floppies::TD0,
    &retro::floppies::A2R,
    &retro::floppies::MOOF,
    &retro::floppies::AMIGA_RDB,
    &retro::systems::SMDH,
    &retro::systems::FIRM,
    &retro::systems::KIP1,
    &retro::systems::INI1,
    &retro::systems::STFS,
    &retro::systems::XISO,
    &retro::micros::CPC_SNA,
    &retro::micros::SZX,
    &retro::micros::RZX,
    &retro::micros::NIB,
    &retro::micros::VICE,
    &retro::micros::ATARI_CAS,
    &retro::micros::ATX,
    &retro::micros::NUFX_ARCHIVE,
    &retro::micros::BINHEX,
    &retro::console_packages::WUX,
    &retro::console_packages::NCZ,
    &retro::console_packages::NPDM,
    &retro::console_packages::PS3_PUP,
    &retro::console_packages::PS4_PKG,
    &retro::console_packages::PSP_PRX,
    &retro::console_packages::SHARKPORT,
    &retro::console_packages::MAME_INP,
    &retro::console_packages::MAME_STATE,
    &retro::graphics::KICKSTART,
    &retro::graphics::AMIGA_INFO,
    &retro::extras::DSV,
    &retro::extras::GC_BANNER,
    &retro::extras::WII_BANNER,
    &retro::extras::TPL,
    &retro::extras::CEL_3DO,
    &retro::extras::HXC_MFM,
    &retro::extras::FDI,
    // Weak probes: trailers and text.
    &retro::discs::NRG,
    &retro::discs::CDI,
    &retro::discs::GDI,
    &retro::cartridges::INTELLIVISION,
    &retro::cartridges::COLECOVISION,
    &retro::cartridges::MSX_ROM,
    &retro::cartridges::WONDERSWAN_COLOR,
    &retro::cartridges::WONDERSWAN,
    &retro::cartridges::VIRTUAL_BOY,
    &retro::states::GCI,
    &retro::states::FM2,
    &retro::tapes::ZX_TAP,
    &retro::tapes::TRD,
    &retro::tapes::ORIC_TAP,
    &retro::tapes::ATARI_ST_PRG,
    &retro::floppies::SCP,
    &retro::floppies::DC42,
    &retro::floppies::D88,
    &retro::systems::DOL,
    &retro::systems::VMI,
    &retro::micros::ZX_SNA,
    &retro::micros::ATARI_XEX,
    &retro::micros::MACBINARY,
    &retro::graphics::DEGAS,
    &retro::graphics::NEOCHROME,
    &retro::graphics::KOALA,
    &retro::graphics::MSX_BSAVE,
    &retro::graphics::AMSDOS,
    &retro::dats::CLRMAMEPRO,
    &retro::dats::LOGIQX,
    &retro::dats::SOFTLIST,
    &retro::dats::CDRDAO_TOC,
    &retro::dats::RETROARCH_CHT,
    // -- end retro --

    // -- ml models & mobile platforms --
    &ml::binary::GGML,
    &ml::binary::GGMF,
    &ml::binary::GGJT,
    &ml::binary::GGLA,
    &ml::binary::NCNN_BIN,
    &ml::binary::MXNET,
    &ml::binary::NNEF_TENSOR,
    &ml::binary::FASTTEXT,
    &ml::binary::MLIR,
    &ml::tflite::TFLITE,
    &ml::tflite::ORT,
    &ml::tflite::EXECUTORCH,
    &mobile::android::SUPER,
    &mobile::android::VENDOR_BOOT,
    &mobile::android::BOOTLDR,
    &mobile::android::MTK,
    &mobile::android::PIT,
    &mobile::android::QCDT,
    &mobile::android::ART_PROFILE,
    &mobile::android::FCONTEXT,
    &mobile::android::HPROF,
    &mobile::android::METHOD_TRACE,
    &mobile::apple::NIB,
    &mobile::apple::METALLIB,
    &mobile::apple::CAR,
    &mobile::apple::CODE_SIGNATURE,
    &mobile::apple::AEA,
    &mobile::apple::SWIFTMODULE,
    &ml::protos::TFRECORD,
    &ml::protos::SAVED_MODEL,
    &ml::protos::COREML,
    &ml::protos::ONNX,
    &ml::protos::GRAPHDEF,
    &ml::protos::SENTENCEPIECE,
    &mobile::apple::TRUSTCACHE,
    &mobile::android::LOGCAT,
    &mobile::android_text::TOMBSTONE_FORMAT,
    &mobile::android_text::ANR,
    &mobile::android_text::BUILD_PROP,
    &mobile::apple_text::PBXPROJ,
    &mobile::apple_text::BCSYMBOLMAP,
    &mobile::apple_text::CRASH,
    &mobile::apple_text::IPS,
    &mobile::apple_text::TBD,
    &mobile::apple_text::STRINGS,
    &ml::text::NCNN,
    &ml::text::CAFFE,
    &ml::text::DARKNET,
    &ml::text::NNEF_GRAPH,
    &ml::text::LIBSVM,
    &ml::text::LIBLINEAR,
    &ml::text::LIGHTGBM,
    &ml::text::OPENVINO,
    &ml::text::PMML,
    &ml::text::OPENCV,
    &ml::text::MXNET_SYMBOL,
    &ml::text::TFJS,
    &ml::text::HF_TOKENIZER,
    &ml::text::SAFETENSORS_INDEX,
    // -- end ml --

    // -- geospatial, telemetry & vehicle logs --
    &geo::fit::FIT,
    &geo::tiles::PMTILES,
    &geo::tiles::FLATGEOBUF,
    &geo::tiles::O5M,
    &geo::tiles::MVT,
    &geo::gis::GDBTABLE,
    &geo::gis::ISO8211,
    &geo::gis::NTV2,
    &geo::gis::CTABLE2,
    &geo::gis::LAZ,
    &geo::gis::GARMIN_IMG,
    &geo::gis::GARMIN_GDB,
    &geo::gis::OV2,
    &geo::gnss::UBX,
    &geo::gnss::RTCM3,
    &geo::gnss::SBF,
    &geo::gnss::NOVATEL,
    &geo::gnss::NMEA,
    &geo::rinex::OBS,
    &geo::rinex::NAV,
    &geo::rinex::MET,
    &geo::rinex::CLOCK,
    &geo::rinex::CRINEX,
    &geo::rinex::ANTEX,
    &geo::rinex::IONEX,
    &geo::rinex::SP3,
    &geo::rinex::SINEX,
    &geo::mdf::MDF,
    &geo::vehicle::BLF,
    &geo::vehicle::ASC,
    &geo::vehicle::CANDUMP,
    &geo::vehicle::TRC,
    &geo::vehicle::DBC,
    &geo::vehicle::LDF,
    &geo::vehicle::A2L,
    &geo::robotics::ULOG,
    &geo::robotics::DATAFLASH,
    &geo::robotics::ARDUPILOT_LOG,
    &geo::robotics::TLOG,
    &geo::robotics::GPMF,
    &geo::robotics::ROSBAG,
    &geo::robotics::MCAP,
    &geo::robotics::BLACKBOX_LOG,
    &geo::gistext::IGC,
    &geo::gistext::OZI_TRACK,
    &geo::gistext::OZI_WAYPOINTS,
    &geo::gistext::OZI_ROUTE,
    &geo::gistext::OZI_MAP,
    &geo::gistext::MIF,
    &geo::gistext::TAB,
    &geo::gistext::GRASS_ASCII,
    &geo::gistext::GRASS_VECTOR,
    &geo::gistext::IDRISI,
    &geo::gistext::WKT,
    &geo::gistext::BIL_HDR,
    &geo::gistext::HRM,
    &geo::gistext::ERG,
    &geo::gistext::SRM,
    &geo::markup::TCX,
    &geo::markup::PWX,
    &geo::markup::FITLOG,
    &geo::markup::ZWO,
    &geo::markup::OSC,
    &geo::markup::GML,
    &geo::markup::ARXML,
    &geo::markup::ODX,
    &geo::markup::TILEJSON,
    &geo::markup::MAPBOX_STYLE,
    &geo::markup::QGC_PLAN,
    // -- end geo --

    // -- publishing, design & multimedia authoring --
    &publishing::adobe::PAT,
    &publishing::adobe::ABR,
    &publishing::adobe::GRD,
    &publishing::adobe::ASL,
    &publishing::adobe::ATN,
    &publishing::adobe::ACB,
    &publishing::adobe::CSH,
    &publishing::adobe::ACV,
    &publishing::fonts::CFF,
    &publishing::fonts::FNT,
    &publishing::fonts::PFM,
    &publishing::fonts::TFM,
    &publishing::fonts::VF,
    &publishing::fonts::AMIGA_FONT,
    &publishing::fonts::PFR,
    &publishing::fonts::BGI,
    &publishing::fonts::VFB,
    &publishing::fonts::SFD,
    &publishing::fonts::GLYPHS,
    &publishing::fonts::GLIF,
    &publishing::fonts::DESIGNSPACE,
    &publishing::dtp::INDESIGN,
    &publishing::dtp::QUARK,
    &publishing::dtp::XARA,
    &publishing::dtp::SCRIBUS,
    &publishing::dtp::XMP,
    &publishing::authoring::HYPERCARD,
    &publishing::authoring::FIGMA,
    &publishing::authoring::RIVE,
    &publishing::authoring::MOC3,
    &publishing::printing::PJL,
    &publishing::printing::PCLXL,
    &publishing::printing::PCL,
    &publishing::printing::CUPS_RASTER,
    &publishing::printing::URF,
    &publishing::printing::PPD,
    &publishing::printing::GPD,
    &publishing::printing::HPGL,
    &publishing::printing::ZPL,
    &publishing::printing::ESCP,
    &publishing::design::ASEPRITE,
    &publishing::design::PICT,
    &publishing::design::JASC_PAL,
    &publishing::design::GGR,
    &publishing::design::CUBE,
    &publishing::design::CGM,
    &publishing::design::GEM,
    // Identified by size alone: last.
    &publishing::adobe::ACT,
    // -- end publishing --

    // -- games, 3D, science, e-books, misc --
    &games::engines::WAD,
    &games::engines::PAK,
    &games::engines::WAD2,
    &games::engines::VPK,
    &games::engines::MDL,
    &games::engines::MD2,
    &games::engines::MD3,
    &games::engines::UNREAL,
    &games::engines::BSP,
    &engineering::models::GLB,
    &engineering::models::FBX,
    &engineering::models::BLEND,
    &engineering::models::USDC,
    &engineering::models::VOX,
    &engineering::models::PLY,
    &engineering::models::DWG,
    &engineering::models::THREE_DS,
    &engineering::models::STL_ASCII,
    &engineering::models::DXF,
    &science::imaging::FITS,
    &science::imaging::DICOM,
    &geo::survey::SHX,
    &geo::survey::SHP,
    &geo::survey::LAS,
    &geo::survey::GRIB,
    &geo::survey::BUFR,
    &geo::survey::DBF,
    &documents::ebooks::MOBI,
    &documents::ebooks::PALMDOC,
    &documents::ebooks::DJVU,
    &documents::ebooks::LIT,
    &security::credentials::KDBX,
    &security::credentials::KDB,
    &security::credentials::OPENSSH_KEY,
    &security::credentials::KEYBOX,
    &security::credentials::KEYCHAIN,
    &security::credentials::ANDROID_BACKUP,
    &system::artifacts::DTB,
    &system::artifacts::BZIMAGE,
    &system::artifacts::JOURNAL,
    &system::artifacts::REDIS_RDB,
    &system::artifacts::PST,
    &system::artifacts::DOTNET_RESOURCES,
    &system::artifacts::SNOOP,
    &system::artifacts::ACPI,
    &image::graphics::EMF,
    &image::graphics::DPX,
    &image::graphics::CINEON,
    &image::graphics::VTF,
    &image::graphics::PVR,
    &image::graphics::ASTC,
    &image::graphics::PKM,
    &image::graphics::ASE,
    &image::graphics::GBR,
    &image::graphics::GPAT,
    &image::graphics::PDN,
    &image::graphics::BPG,
    &image::graphics::FLIF,
    &image::graphics::JXR,
    &image::graphics::WMF,
    &image::graphics::ACO,
    &games::packages::GODOT_PCK,
    &games::packages::UNITYFS,
    &games::packages::GAMEMAKER,
    &games::packages::RPA,
    &compression::containers::APPLE_ARCHIVE,
    &compression::containers::LZFSE,
    &compression::containers::PBZX,
    &compression::containers::LZOP,
    &compression::containers::LZF,
    &compression::containers::LRZIP,
    &compression::containers::ZSTD_DICT,
    &compression::containers::POWERPACKER,
    &compression::containers::ZPAQ,
    &video::pgs::PGS,
    &games::archives::SARC,
    &games::archives::YAZ0,
    &games::archives::U8,
    &games::archives::NARC,
    &games::archives::PSARC,
    &games::archives::XNB,
    &games::archives::BSA,
    &games::archives::BA2,
    &games::archives::MPQ,
    &games::archives::RGSSAD,
    &audio::cool_edit::SES,
    &audio::projects::FXP,
    &audio::projects::FLP,
    &audio::guitar_pro::FORMAT,
    &audio::guitar_pro::gpx::FORMAT,
    &games::archives::UNREAL_PAK,
    &documents::dvi::DVI,
    &documents::wordprocessing::WORDPERFECT,
    &documents::wordprocessing::WRITE,
    &documents::wordprocessing::ONENOTE,
    &documents::wordprocessing::FRAMEMAKER,
    &archive::warc::WARC,
    &security::age::AGE,
    &data::bitcoin::BITCOIN_BLOCKS,
    &pcap::captures::BTSNOOP,
    &pcap::captures::NETMON,
    &system::ota::OTA_PAYLOAD,
    &forensics::registry_pol::REGISTRY_POL,
    &data::ese::ESE,
    &system::bom::BOMSTORE,
    &system::shim_sdb::SDB,
    &science::datasets::SPSS,
    &science::datasets::SAS7BDAT,
    &science::datasets::STATA,
    &science::datasets::ROOT,
    &science::datasets::NIFTI,
    &science::datasets::NRRD,
    &science::datasets::HDF4,
    &science::datasets::VTK,
    &executable::pdb::PDB,
    &executable::pdb::PDB2,
    &system::platform::PERF,
    &system::platform::LDSO_CACHE,
    &system::platform::SELINUX,
    &system::platform::VBMETA,
    &system::platform::DTBO,
    &system::platform::INTEL_FLASH,
    &system::platform::CBFS,
    &system::platform::ARM_FIP,
    &system::platform::NSIS,
    &system::platform::INNO,
    &system::platform::JMOD,
    &system::platform::JIMAGE,
    &system::platform::MAC_RESOURCE,
    &system::devices::ROMFS,
    &system::devices::JFFS2,
    &system::devices::UBI,
    &system::devices::UBIFS,
    &system::devices::TRX,
    &system::devices::IMG3,
    &system::devices::XEX,
    &system::devices::PS3_SELF,
    &system::devices::PS3_PKG,
    &system::devices::NSP,
    &system::devices::XCI,
    &system::devices::WII_WAD,
    &system::devices::CIA,
    &system::devices::KERNEL_DUMP,
    // NTFS $LogFile restart pages also start with RSTR; check them first.
    &forensics::windows::LOGFILE,
    &system::devices::HIBERFIL,
    &system::devices::VERITY,
    &system::devices::BTRFS_SEND,
    &system::devtools::GCC_PCH,
    &system::devtools::CLANG_PCH,
    &system::devtools::WIN_RES,
    &system::delphi::DFM,
    &system::devtools::ILK,
    &system::devtools::TYPELIB,
    &system::devtools::NAR,
    &system::devtools::GIT_BUNDLE,
    &system::devtools::HG_BUNDLE,
    &system::devtools::SVN_DUMP,
    &system::devtools::DUCKDB,
    &system::devtools::LMDB,
    &system::devtools::BOLT,
    &system::devtools::PROM_CHUNKS,
    &system::devtools::PROM_INDEX,
    &system::devtools::INFLUX_TSM,
    &system::devtools::LUCENE,
    &documents::ebooks::PDB,
    // bioinformatics (BGZF-based ones are listed before gzip)
    &science::bio::binary::BAI,
    &science::bio::binary::CRAM,
    &science::bio::binary::TWOBIT,
    &science::bio::binary::BIGWIG,
    &science::bio::binary::BIGBED,
    &science::bio::binary::ABIF,
    &science::bio::binary::SCF,
    &science::bio::text::VCF,
    &science::bio::text::SAM,
    &science::bio::text::GFF3,
    &science::bio::text::GENBANK,
    &science::bio::text::STOCKHOLM,
    &science::bio::text::CLUSTAL,
    &science::bio::text::MAF,
    &science::bio::text::NEXUS,
    &science::bio::text::GFA,
    &science::bio::text::JCAMP,
    &science::bio::text::PDB_STRUCTURE,
    &science::bio::text::SDF,
    &science::bio::text::MOLFILE,
    &science::bio::text::CIF,
    &science::bio::text::WIG,
    &science::bio::text::BED,
    &science::bio::text::FASTQ,
    &science::bio::text::FASTA,
    &science::instruments::FCS,
    &science::instruments::THERMO_RAW,
    &science::instruments::ABF,
    &science::instruments::ABF2,
    &science::instruments::EDF,
    &science::instruments::BDF,
    &science::instruments::GDF,
    &science::instruments::INTAN_RHD,
    &science::instruments::TDMS,
    &science::instruments::TDMS_INDEX,
    &science::instruments::NEV,
    &science::instruments::NSX,
    &science::instruments::PLEXON,
    &science::instruments::BRAINVISION_HEADER,
    &science::instruments::BRAINVISION_MARKERS,
    &science::instruments::NEURALYNX,
    &science::instruments::IDX,
    &geo::geoscience::SEGY,
    &geo::geoscience::SEG2,
    &geo::geoscience::MSEED3,
    &geo::geoscience::SAC,
    &geo::geoscience::ERDAS_IMG,
    &geo::geoscience::E57,
    &geo::geoscience::PCD,
    &geo::geoscience::LAS_LOG,
    &geo::geoscience::SURFER_GRID,
    &geo::geoscience::ESRI_GRID,
    &geo::geoscience::ENVI_HDR,
    &geo::geoscience::PDS3,
    &geo::geoscience::VICAR,
    &geo::geoscience::MSEED2,
    &engineering::eda::GDSII,
    &engineering::eda::OASIS,
    &engineering::eda::KICAD_PCB,
    &engineering::eda::KICAD_SCH,
    &engineering::eda::KICAD_SYM,
    &engineering::eda::KICAD_MOD,
    &engineering::eda::EDIF,
    &engineering::eda::SDF_TIMING,
    &engineering::eda::VCD,
    &engineering::eda::CITI,
    &engineering::eda::SPICE_RAW,
    &engineering::eda::IBIS,
    &engineering::eda::SPEF,
    &engineering::eda::XILINX_BIT,
    &engineering::eda::JEDEC,
    &engineering::eda::EXCELLON,
    &engineering::eda::GERBER,
    &engineering::eda::TOUCHSTONE,
    &engineering::fabrication::BGCODE,
    // G-code has no magic: a strict content probe, after Gerber/Excellon.
    &engineering::fabrication::GCODE,
    &forensics::browser::IE_INDEX,
    &forensics::browser::BINARYCOOKIES,
    &forensics::browser::CHROME_CACHE_INDEX,
    &forensics::browser::CHROME_CACHE_BLOCK,
    &forensics::browser::CHROME_SIMPLE,
    &forensics::browser::CHROME_VISITED,
    &forensics::browser::SNSS,
    &forensics::browser::MORK,
    &forensics::windows::CUSTOM_DESTINATIONS,
    &forensics::windows::INFO2,
    &forensics::windows::MFT,
    &forensics::windows::INDX,
    &forensics::windows::JOB,
    &forensics::windows::NK2,
    &forensics::windows::DBX,
    &forensics::windows::RDP_CACHE,
    &forensics::windows::SCF,
    &forensics::windows::GRP,
    &forensics::windows::CARDFILE,
    &forensics::windows::CLP,
    &forensics::windows::USN,
    &forensics::unix::FSEVENTS,
    &forensics::unix::TIMESYNC,
    &forensics::unix::TRACEV3,
    &forensics::unix::ASL,
    &forensics::unix::MBDB,
    &forensics::unix::ABX,
    &forensics::unix::UTMPX,
    &forensics::unix::UUIDTEXT,
    &forensics::unix::MBDX,
    &forensics::browser::CHROME_SIMPLE_INDEX,
    &documents::office_legacy::LOTUS,
    &documents::office_legacy::LOTUS3,
    &documents::office_legacy::QUATTRO,
    &documents::office_legacy::WORKS_WKS,
    &documents::office_legacy::XLS_BIFF,
    &documents::office_legacy::CLARISWORKS,
    &documents::office_legacy::SKETCHUP,
    &documents::office_legacy::SYLK,
    &documents::office_legacy::DIF,
    &documents::office_legacy::QIF,
    &documents::office_legacy::OFX,
    &documents::office_legacy::MPX,
    &documents::office_legacy::AMIPRO,
    &documents::office_legacy::MONEY,
    &documents::office_legacy::WORDPRO,
    &forensics::windiag::WER,
    &forensics::windiag::PIF,
    &forensics::logs::SETUPAPI,
    &forensics::logs::W3C,
    &forensics::logs::TRANSCRIPT,
    &forensics::logs::AUDIT,
    &forensics::logs::VIMINFO,
    &forensics::evidence::EWF,
    &forensics::evidence::AFF,
    &forensics::evidence::LIME,
    &forensics::evidence::KDUMP,
    &forensics::evidence::VMSS,
    &forensics::evidence::VBOX_SAV,
    &forensics::userdata::ZSH,
    &forensics::userdata::BASH,
    &forensics::userdata::FISH,
    &forensics::userdata::LIBEDIT,
    &forensics::userdata::LESS,
    &forensics::userdata::WGET_HSTS,
    &forensics::userdata::COOKIES_TXT,
    &forensics::userdata::BOOKMARKS,
    &forensics::userdata::OPERA_HOTLIST,
    &forensics::userdata::FIREFOX_PREFS,
    &forensics::userdata::CERT_OVERRIDE,
    &forensics::userdata::TRASHINFO,
    &forensics::userdata::XBEL,
    &security::keyrings::GNOME_KEYRING,
    &security::keyrings::KWALLET,
    &documents::office_legacy::WINWORD2,
    &documents::office_legacy::HWP3,
    &documents::office_legacy::HWP5_HEADER,
    &forensics::windows::ODL,
    &geo::osm::OSM_PBF,
    &geo::elevation::DTED,
    &geo::elevation::NITF,
    &archive::minor::ALZ,
    &archive::minor::EGG,
    &archive::minor::KGB,
    &archive::minor::ISCAB,
    &archive::minor::ISZ,
    &image::camera::PHOTO_CD,
    &image::camera::X3F,
    &video::subtitles::EBU_STL,
    &video::subtitles::SCC,
    &video::subtitles::VOBSUB,
    &video::nut::NUT,
    &engineering::meshes::VRML,
    &engineering::meshes::OFF,
    &engineering::meshes::MD5MESH,
    &engineering::meshes::SOURCE_MDL,
    &engineering::meshes::PSK,
    &documents::lrf::LRF,
    &font::adobe::AFM,
    &font::adobe::PFA,
    &games::blizzard::BLP,
    &games::blizzard::M2,
    &games::blizzard::W3M,
    &games::bethesda::TES,
    &games::packfiles::GTA_IMG,
    &games::packfiles::HOG,
    &games::packfiles::GRP,
    &games::packfiles::BIG,
    &games::packfiles::RFF,
    &games::packfiles::BND,
    &games::nw4::NW4,
    &games::nw4::NW4R,
    &audio::sequenced::MUS,
    &audio::sequenced::HMI,
    &audio::sequenced::AHX,
    &audio::sequenced::MO3,
    &audio::sequenced::DBM,
    &audio::sequenced::FAR,
    &font::raster::PSF_FONT,
    &font::raster::BMFONT,
    &font::raster::FIGLET,
    &font::raster::TEX_PK,
    &font::raster::TEX_GF,
    &security::putty::PPK,
    &audio::pcm_headers::SPHERE,
    &audio::pcm_headers::AVR,
    &audio::pcm_headers::PVF,
    &image::toolkits::MIFF,
    &image::toolkits::UTAH_RLE,
    &image::toolkits::PSP,
    &games::middleware::FSB,
    &games::middleware::XWB,
    &games::middleware::WWISE_BNK,
    &games::middleware::VAG,
    &games::middleware::OMA,
    &games::middleware::HCA,
    &games::middleware::USM,
    &games::middleware::CPK,
    &games::middleware::AFS,
    &games::middleware::EA_SCHL,
    &video::containers::NSV,
    &video::containers::NUV,
    &video::containers::R3D,
    &video::containers::DPAINT_ANM,
    &audio::production::TWINVQ,
    &audio::production::EXS,
    &audio::production::PTAB,
    &engineering::cad::STEP,
    &engineering::cad::IGES,
    &engineering::cad::PARASOLID,
    &engineering::cad::JT,
    &engineering::cad::GMSH,
    &engineering::cad::OPENFOAM,
    &engineering::cad::ABAQUS,
    &engineering::cad::LSDYNA,
    &science::microscopy::MRC,
    &science::microscopy::CZI,
    &science::microscopy::ND2,
    &science::microscopy::LIF,
    &science::microscopy::SER,
    &science::microscopy::GATAN_DM,
    &science::molecular::DCD,
    &science::molecular::XTC,
    &science::molecular::TRR,
    &science::molecular::MOL2,
    &science::molecular::CHARMM_PSF,
    &science::molecular::MSP,
    &science::molecular::MGF,
    &science::spectroscopy::NMRPIPE,
    &science::spectroscopy::SPARKY,
    &science::spectroscopy::RIGAKU_RAS,
    &science::lab_images::IMAGEJ_ROI,
    &science::lab_images::PRINCETON_SPE,
    &science::lab_images::ICS,
    &science::lab_images::IMOD,
    &science::lab_images::FREESURFER_SURF,
    &science::waveforms::SPIKE2,
    &science::waveforms::AXON_ATF,
    &science::waveforms::IGOR_ITX,
    &science::waveforms::LABVIEW_LVM,
    &science::waveforms::KEYSIGHT_BIN,
    &science::waveforms::TEKTRONIX_ISF,
    &science::waveforms::LECROY_TRC,
    &science::waveforms::FST,
    &science::lab_images::BIORAD_PIC,
    &science::lab_images::MGH,
    &science::lab_images::ANALYZE,
    &science::spectroscopy::GALACTIC_SPC,
    &science::bio::sequencing::SFF,
    &science::bio::sequencing::ZTR,
    &science::bio::sequencing::SLOW5,
    &science::bio::sequencing::BLOW5,
    &science::bio::sequencing::HIC,
    &science::bio::records::HMMER3,
    &science::bio::records::EMBL,
    &science::bio::records::PSL,
    &science::bio::records::MZTAB,
    &science::bio::records::AMBER_PRMTOP,
    &science::bio::records::GTF,
    &engineering::brep::RHINO_3DM,
    &engineering::brep::ACIS_SAB,
    &engineering::simulation::ANSYS_CDB,
    &engineering::simulation::TECPLOT,
    &engineering::simulation::ENSIGHT_CASE,
    &engineering::simulation::ENSIGHT_GOLD,
    &engineering::simulation::OPENVDB,
    &engineering::simulation::NASTRAN,
    &geo::dlis::ERMAPPER_ERS,
    &geo::dlis::DLIS,
    &engineering::eda::SAIF,
    &engineering::eda::SPECCTRA_DSN,
    &engineering::eda::SPECCTRA_SES,
    &engineering::eda_text::LTSPICE_ASC,
    &engineering::eda_text::LTSPICE_ASY,
    &engineering::eda_text::KICAD_LEGACY_SCH,
    &engineering::eda_text::KICAD_LEGACY_LIB,
    &engineering::eda_text::KICAD_LEGACY_PCB,
    &engineering::eda_text::GEDA_SCH,
    &engineering::eda_text::PADS_ASCII,
    &engineering::eda_text::DEF,
    &engineering::eda_text::LEF,
    &archive::legacy::HA,
    &archive::legacy::UHARC,
    &archive::legacy::YZ1,
    &archive::legacy::DGCA,
    &archive::legacy::GCA,
    &archive::legacy::PAQ8,
    &compression::legacy::FREEZE,
    &compression::legacy::COMPACT,
    &archive::legacy::XPK,
    &archive::legacy::AMIGA_LZX,
    &archive::legacy::PACKIT,
    &image::paint::CPT,
    &image::paint::CLIP,
    &image::paint::MDP,
    &image::paint::GIMP_GPL,
    &image::minor::PGF,
    &image::minor::XV_THUMB,
    &image::minor::VIFF,
    &documents::help::OS2_INF,
    &documents::help::TCR,
    &documents::help::AMIGAGUIDE,
    &data::embedded_db::TOKYO,
    &data::embedded_db::KYOTO,
    &data::embedded_db::GDBM,
    &data::embedded_db::RRD,
    &data::embedded_db::WIREDTIGER,
    &data::embedded_db::REALM,
    &security::kerberos::KEYTAB,
    &security::kerberos::CCACHE,
    &security::encryption::PWSAFE,
    &security::encryption::OPENSSL_ENC,
    &security::encryption::AESCRYPT,
    &security::encryption::AXCRYPT,
    &security::encryption::MINISIGN,
    &data::dumps::MTF,
    &data::dumps::ORACLE_EXP,
    &data::dumps::PG_DUMP,
    &data::dumps::MYSQL_FRM,
    &data::dumps::MYISAM,
    &data::dumps::H2,
    &data::dumps::FILEMAKER,
    &data::rdata::R_DATA,
    &data::rdata::ASDF,
    &forensics::wab::WAB,
    &bytecode::applescript::APPLESCRIPT,
    &archive::packaging::SOLARIS_PKG,
    &archive::packaging::HPKG,
    &archive::packaging::ASAR,
    &games::models::DIRECTX_X,
    &games::models::MS3D,
    &games::models::CAL3D,
    &games::models::OGRE,
    &engineering::dcc::MAYA,
    &engineering::dcc::C4D,
    &engineering::dcc::BGEO,
    &engineering::dcc::ALEMBIC,
    &games::models::NIF,
    &games::engine_data::HKX,
    &games::engine_data::BGSM,
    &games::engine_data::WOW_CHUNKED,
    &games::engine_data::WOW_DB,
    &games::engine_data::WC3_MDX,
    &games::models::QUAKE_SPR,
    &games::models::QUAKE2_SP2,
    &games::models::RTCW_MODEL,
    &games::models::HEXEN2_MDL,
    &games::models::VVD,
    &games::models::DMX,
    &games::engine_data::UTOC,
    &games::engine_data::XP3,
    &games::engine_data::ALLEGRO,
    &games::engine_data::RPYC,
    &games::consoles::BFRES,
    &games::consoles::BNTX,
    &games::consoles::MSBT,
    &games::consoles::CGFX,
    &games::consoles::J3D,
    &games::consoles::RARC,
    &games::consoles::BRRES,
    &games::consoles::GIM,
    &games::consoles::GXT,
    &games::consoles::RCO,
    &games::consoles::NPD,
    &games::consoles::XDBF,
    &games::consoles::XPR,
    &games::consoles::XACT,
    &games::consoles::SEGA_TEXTURE,
    &games::consoles::NINJA,
    &tracker::pc::PTM,
    &tracker::pc::DMF,
    &tracker::pc::IMF,
    &tracker::pc::J2B,
    &tracker::pc::GDM,
    &tracker::pc::MT2,
    &tracker::pc::AMS,
    &tracker::pc::SYMPHONIE,
    &tracker::pc::DIGITRAKKER,
    &tracker::pc::PLM,
    &tracker::pc::PSM,
    &tracker::pc::AMF,
    &tracker::pc::GUS_PAT,
    &audio::codecs::REALAUDIO,
    &audio::codecs::PSION_WVE,
    &audio::codecs::EVS,
    &video::movies::SMUSH,
    &video::movies::DXA,
    &video::movies::ARMOVIE,
    &video::movies::SGI_MOVIE,
    // Weak, size-based probes last.
    &games::consoles::BYML,
    &compression::legacy::SQUEEZE,
    &compression::legacy::CRUNCH,
    &games::minecraft::NBT,
    &geo::elevation::HGT,
    &forensics::unix::UTMP,
    &forensics::browser::FIREFOX_CACHE2,
    &forensics::logs::ACCT,
    &forensics::windows::RDP_FILE,
    &forensics::unix::LASTLOG,
    &forensics::windows::DESTLIST,
    &forensics::windows::AUTORUN,
    &forensics::windows::DESKTOP_INI,
    &engineering::models::STL,
    // A ZIP after a stub or other data (its end record at the very end).
    &archive::zip::PREFIXED,
    // -- end misc --

    // -- text (generic probes, keep last) --
    // Documents with a fixed signature.
    &text::rtf::FORMAT,
    &text::postscript::DOS_EPS,
    &text::postscript::EPS,
    &text::postscript::POSTSCRIPT,
    // Binary formats found inside text armor.
    &text::ssh::BLOB,
    // Armor and keys.
    &text::pem::SSH2,
    &text::ssh::KEYS,
    // Messages (header blocks look like YAML; keep them before it).
    &text::mime::MBOX,
    &text::mime::MHTML,
    &text::mime::EML,
    &text::yenc::FORMAT,
    &text::ldif::FORMAT,
    &text::diff::FORMAT,
    &text::vcard::VCARD,
    &text::vcard::ICALENDAR,
    // Timed text and playlists.
    &text::subtitles::WEBVTT,
    &text::subtitles::SRT,
    &text::subtitles::LRC,
    &text::playlist::HLS,
    &text::playlist::M3U,
    &text::playlist::PLS,
    &text::playlist::CUE,
    &text::subtitles::MICRODVD,
    &text::sln::FORMAT,
    &text::klc::FORMAT,
    &text::dockerfile::FORMAT,
    &text::dot::FORMAT,
    // Line-oriented data with distinctive keywords.
    &text::uuencode::FORMAT,
    &text::po::FORMAT,
    &text::bibtex::FORMAT,
    &text::checksums::FORMAT,
    &text::obj::OBJ,
    &text::obj::MTL,
    // Markup: specific XML vocabularies, then HTML, then generic XML.
    &text::plist::FORMAT,
    &text::xml::XHTML,
    &text::xml::SVG,
    &text::xml::RSS,
    &text::xml::ATOM,
    &text::xml::GPX,
    &text::xml::KML,
    &text::xml::POM,
    &text::xml::XAML,
    &text::xml::MATHML,
    &text::xml::XSLT,
    &text::xml::XSD,
    &text::xml::MSBUILD,
    &text::xml::COLLADA,
    &text::xml::TTML,
    &text::xml::DASH,
    &text::xml::XLIFF,
    &text::xml::OPF,
    &text::xml::OSM,
    &text::xml::XSPF,
    &text::xml::TEI,
    &text::xml::DOCBOOK,
    &text::xml::ANDROID_MANIFEST,
    &text::xml::WSDL,
    &text::xml::SOAP,
    &text::xml::SITEMAP,
    &text::xml::DRAWIO,
    &text::xml::OPML,
    &text::xml::FB2,
    &text::xml::GRAPHML,
    &text::xml::SMIL,
    &text::xml::NZB,
    &text::xml::JUNIT,
    &text::xml::MUSICXML,
    &audio::guitar_pro::gpif::FORMAT,
    &text::xml::X3D,
    &text::xml::WIX,
    &text::xml::NUSPEC,
    &text::xml::XIB,
    &text::xml::GLADE,
    &text::xml::FLAT_ODF,
    &text::xml::VSTEMPLATE,
    &text::html::FORMAT,
    &text::xml::FORMAT,
    // JSON and its vocabularies.
    &text::json::IPYNB,
    &text::json::GLTF,
    &text::json::JSON_SCHEMA,
    &text::json::TOPOJSON,
    &text::json::WEB_MANIFEST,
    &text::json::EXTENSION_MANIFEST,
    &text::json::LOTTIE,
    &text::json::EXCALIDRAW,
    &text::json::SARIF,
    &text::json::OPENAPI,
    &text::json::TSCONFIG,
    &text::json::NPM_PACKAGE,
    &text::json::GEOJSON,
    &text::json::HAR,
    &text::json::NDJSON,
    &text::json::FORMAT,
    // TOML before INI: its values are typed, INI's are not.
    &text::ini::EDITORCONFIG,
    &text::toml::FORMAT,
    // INI family: specific first.
    &text::ini::REG,
    &text::ini::DESKTOP,
    &text::ini::URL,
    &text::ini::SYSTEMD,
    &text::ini::INF,
    &text::ini::ASS,
    &text::ini::FORMAT,
    // Markdown before YAML: front matter starts like a YAML document.
    &text::markdown::FORMAT,
    &text::yaml::KUBERNETES,
    &text::yaml::COMPOSE,
    &text::yaml::GITHUB_WORKFLOW,
    &text::yaml::OPENAPI,
    &text::yaml::FORMAT,
    &text::plain::SCRIPT,
    // Brotli has no magic: only small files that decode as exactly one
    // complete stream (a trial decode, so after everything with magic).
    &compression::brotli::FORMAT,
    // Weak, statistical probes.
    &text::csv::TSV,
    &text::csv::CSV,
    // Plain text matches anything textual: keep it last.
    &text::plain::FORMAT,
    // -- end text --
];

pub fn by_name(name: &str) -> Option<&'static Format> {
    FORMATS.iter().copied().find(|f| f.name == name)
}

/// Picks the first format whose probe matches.
pub fn identify(head: &Head<'_>) -> Option<&'static Format> {
    FORMATS.iter().copied().find(|f| f.probe.matches(head))
}

/// A top-level node that identifies and dissects `span` when expanded.
pub fn root(name: impl Into<Cow<'static, str>>, span: Span) -> Node {
    Node::new(name).span(span).lazy(dissect, Input::root(span))
}

/// A node for embedded content, identified and dissected on expansion.
pub fn embedded(name: impl Into<Cow<'static, str>>, input: Input) -> Node {
    Node::new(name).span(input.span).lazy(dissect, input)
}

/// A node for embedded content of a known format.
pub fn embedded_as(
    name: impl Into<Cow<'static, str>>,
    input: Input,
    format: &'static Format,
) -> Node {
    Node::new(name)
        .span(input.span)
        .lazy(dissect_as, (input, format.name))
}

fn check_nesting(cx: &Cx, input: &Input) -> Result<()> {
    let max = cx.limits().max_nesting;
    if input.nesting > max {
        return Err(
            Diagnostic::limit(format!("embedded objects nested deeper than {max}")).at(input.span),
        );
    }
    Ok(())
}

/// Reads what probes need: the head and the tail of the input.
pub async fn head(cx: &Cx, span: Span) -> Result<(Vec<u8>, Vec<u8>)> {
    let max = cx.limits().max_read;
    let data = cx.read_avail(span.sub(0, HEAD_LEN.min(max))).await?;
    // Reading the tail of a lazily decoded stream would decode all of it.
    let tail = if span.len > HEAD_LEN && cx.is_lazy(span.source) {
        Vec::new()
    } else if span.len > HEAD_LEN {
        cx.read_avail(span.tail(span.len.saturating_sub(TAIL_LEN.min(max))))
            .await?
    } else {
        data.clone()
    };
    Ok((data, tail))
}

/// Identifies the format of `input` and dissects it.
pub async fn dissect(cx: Cx, input: Input) -> Result<()> {
    check_nesting(&cx, &input)?;
    let (data, tail) = head(&cx, input.span).await?;
    let probe = Head {
        data: &data,
        tail: &tail,
        len: input.span.len,
    };
    match identify(&probe) {
        Some(format) => (format.dissect)(cx, input).await,
        None if data.is_empty() => Err(Diagnostic::note("empty").at(input.span)),
        None => Err(Diagnostic::unsupported("unrecognized format").at(input.span)),
    }
}

/// Dissects `input`, or, if its format is not recognised, shows it as a
/// plain data leaf so its bytes stay reachable (e.g. decompressed content).
pub async fn dissect_or_data(cx: Cx, input: Input) -> Result<()> {
    check_nesting(&cx, &input)?;
    let (data, tail) = head(&cx, input.span).await?;
    let probe = Head {
        data: &data,
        tail: &tail,
        len: input.span.len,
    };
    match identify(&probe) {
        Some(format) => (format.dissect)(cx, input).await,
        None => {
            cx.emit(Node::new("Data").span(input.span));
            Ok(())
        }
    }
}

/// Members larger than this are decompressed lazily rather than up front.
const LAZY_THRESHOLD: u64 = 1024 * 1024;

pub use crate::codec::Codec;

/// A node for content stored in `span` with `codec`. Nothing is read or
/// decompressed until it is expanded; then the content is decoded into a
/// derived source and dissected in place.
pub fn content(
    name: impl Into<Cow<'static, str>>,
    input: Input,
    span: Span,
    codec: Codec,
    expected: Option<u64>,
) -> Node {
    Node::new(name)
        .span(span)
        .lazy(expand_content, (input, span, codec, expected))
}

/// Expands a content node in place: what [`content`] does on expansion, for
/// expanders that work out the decoded size themselves first.
pub async fn expand_content(
    cx: Cx,
    (input, span, codec, expected): (Input, Span, Codec, Option<u64>),
) -> Result<()> {
    let inner = match codec {
        Codec::Stored => input.nested(span),
        // Large members are decoded lazily: listing the first entries of a
        // multi-gigabyte tarball only decodes what those entries need. A
        // claimed size beyond the codec's maximum ratio is bogus and gets the
        // eager path (which reports the real size).
        codec
            if expected.is_some_and(|e| {
                e > LAZY_THRESHOLD && e <= span.len.saturating_mul(codec.max_ratio())
            }) =>
        {
            let len = expected.unwrap_or(0);
            let decoded = cx.decode_lazy(span, &codec, len)?;
            cx.annotate(format!("{len:#x} bytes, decoded on demand"));
            input.nested(decoded)
        }
        codec => {
            let decoded = crate::codec::decode_span(&cx, span, &codec, expected).await?;
            cx.annotate(format!("{:#x} bytes {}", decoded.span.len, codec.verb()));
            if let Some(e) = decoded.error {
                cx.diag(e);
            } else if decoded.consumed < span.len {
                cx.diag(Diagnostic::note(format!(
                    "{:#x} bytes follow the encoded stream",
                    span.len.saturating_sub(decoded.consumed)
                )));
            }
            input.nested(decoded.span)
        }
    };
    dissect_or_data(cx, inner).await
}

async fn dissect_as(cx: Cx, (input, name): (Input, &'static str)) -> Result<()> {
    check_nesting(&cx, &input)?;
    let format =
        by_name(name).ok_or_else(|| Diagnostic::internal(format!("unknown format {name}")))?;
    (format.dissect)(cx, input).await
}
