// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1700000000);
user_pref("browser.download.dir", "/home/alice/Downloads/secret");
user_pref("browser.startup.homepage", "https://www.example.com/");
user_pref("browser.tabs.warnOnClose", false);
user_pref("network.cookie.cookieBehavior", 5);
user_pref("signon.rememberSignons", true);
